### ISSUE TITLE
Rounding issues ?

### ISSUE THREAD

**Issue by AxelGilbert** [deltapi/abc-feedback#11]
Hi,
Looks like there are rounding issues in the project, it gave me strange abc triplets such as : 
223 + 2276897430419921652 = 2276897430419922000
and
3345519106105278464 + 4630434214219140625 = 7975953320324420000

Best regards

(sorry I hadn't noticed this bug was already reported, please ignore)

**Comment by deltapi** [comment]
Thanks anyways for reporting!
