### ISSUE TITLE
502 (Bad Gateway)

### ISSUE THREAD

**Issue by AaronStephens** [deltapi/abc-feedback#21]
Periodically the API fails to accept results.  
Suggest the client implement a submit queue with an exponential backoff for retries. (especially for non-null results, where CPU time was spent)  If a queue isn't desired, at least retry submitting non-null results a few times over a minute or two, asynchronously if possible.
The queueing solution would be most useful when the client is running in an auto-run mode.  

> worker starts processing {low_a: '1181', high_a: '1182', low_b: '2113', high_b: '2114'}
> process-worker.884b34ac.js:1 worker result {"low_a":"1181","high_a":"1182","low_b":"2113","high_b":"2114","result":[]}
> index.2ec34438.js:1 send to server {"low_a":"1181","high_a":"1182","low_b":"2113","high_b":"2114","result":[],"name":"Aaron B Stephens"}
> index.2ec34438.js:1 POST https://abc.tngtech.com/api/intervalls/result 502 (Bad Gateway)

**Comment by deltapi** [comment]
We deployed a fix for exponential backoff if the server is unavailable for a short amount of time. Please retest and close when possible.

**Comment by deltapi** [comment]
Closing, since there was no response up to now
