### ISSUE TITLE
Implement auto-restart until otherwise said

### ISSUE THREAD

**Issue by deltapi** [deltapi/abc-feedback#3]

**Comment by lukastaegert** [comment]
I was thinking the same. This would require continuous feedback for the user to keep them entertained. Maybe the "start" button could turn into a "stop" button once it is running, and pressing the "stop" button will finish the currently running block before finishing (so that no progress is lost, as opposed to just closing the browser tab).

Alternatively when running in this mode, the frontend could give a short message each time a block is reported back to the server so they know what progress has been persisted. But I am not sure whether this is more confusing to the user.

**Comment by harryhinch** [comment]
Agreed! Having an official automatic mode would be really nice.

In the meantime I threw together a hacky auto-clicker, pasted into the console. Running firefox on windows 10.
```
var auto_timeout;
var start_button = document.getElementsByTagName('input')[1]; // button has no ID, this is likely to break later
function auto_click()
{
  let timer = 1000;
  if(!start_button.disabled)
  {
    setTimeout(()=>{
      document.getElementsByTagName('input')[1].click();
      console.log('click!')
    },2000);
    timer = 3000;
  }
  else console.log('waiting...');
  auto_timeout = setTimeout(auto_click, timer);
}
auto_click();
////// to stop auto clicking:
// clearTimeout(auto_timeout);
```

**Comment by nikipuk** [comment]
I think this, together with #1 would give users a good incentive to keep the website running for a while.

**Comment by deltapi** [comment]
Thank you @nikipk for your feedback, and special thanks to @harryhinch for the automation. This is indeed on our roadmap, stay tuned!

**Comment by JohnyDL** [comment]
Show sums as they're found. This is especially important for continuous searching it looking like it's doing nothing for a long while sucks especially if it gets to the end and pops out multiple entries.

**Comment by KaustubhRakhade** [comment]
I also have my own unofficial automatic mode (It generates table as it finds numbers and color codes then based on their quality)

```
var start_button = document.getElementsByTagName('input')[1];

table = document.createElement('table');
table.setAttribute('id', 'goodtable');
table.setAttribute('rules', 'all');
table.innerHTML = `<tbody><tr><th>rad(a)</th><th>rad(b)</th><th>a</th><th>b</th><th>c</th><th>q</th></tr></tbody>`;

style = document.createElement('style');
style.innerHTML = `
table {
  font-size: 0.8rem;
  color: #333;
  width: 100%;
  text-align: center;
  border: 1px solid gray;
}
th {
  color: #fff;
  background: var(--tng-blue);  
}`;

document.getElementById('app').append(style);
document.getElementById('app').append(table);

function click() {
  if (!start_button.disabled) {
    result = document.querySelector("#app > div > div").childNodes
    if (result[0].textContent.split(' ')[2] > 0) {
      rad_a = result[0].textContent.split(' ')[5];
      rad_b = result[0].textContent.split(' ')[10]
      for (i=1; i<result.length-2; i+=2) {
        let row = document.createElement('tr');
        a = result[i].textContent.split(' ')[0];
        b = result[i].textContent.split(' ')[2];
        c = result[i].textContent.split(' ')[4];
        q = result[i+1].textContent.split('=')[1];
        row.innerHTML = `<td>${rad_a}</td>
                          <td>${rad_b}</td>
                          <td>${a}</td>
                          <td>${b}</td>
                          <td>${c}</td>
                          <td>${q}</td>`
        row.style.backgroundColor = `rgba(0, 127, 255, ${q-1})`;
        document.querySelector('#goodtable').append(row)
      }
    }
    start_button.click();
    console.log('click!');
  }
}

setInterval(()=>{click();}, 100);
```
I know the code is a bit "dirty" :)

**Comment by saraneth0o** [comment]
A temporary solution for some people, maybe? My main browser is Firefox. I am however running this on Edge, as no auto clicker add-ons for Firefox seem to work. Chrome would work too. Just have several tabs open in the background, with the add-on clicking start every 5 seconds per tab.

https://chrome.google.com/webstore/detail/auto-clicker/cpedeojecpbkcomgcolphimkjdnikbck

**Comment by deltapi** [comment]
Continuous mode is active since quite a while now, closing the issue
